package com.mycompany.projectransportationmangementsystem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.mycompany.projectransportationmangementsystem.Manager;
import com.mycompany.projectransportationmangementsystem.Vehicle;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author lenovo
 */
public class MangerForm extends javax.swing.JFrame {
 private static final String TRIP_FILENAME = "trips.txt";
    private static final String VEHICLE_FILENAME = "vehicle.txt";
    private static final String EMPLOYEE_FILENAME = "employee.txt";
    /**
     * Creates new form MangerForm
     */
    public MangerForm() {
        initComponents();
    }
  
     Scanner input = new Scanner(System.in);
     Manager manager = new Manager("mohamed","3050417","Manger","23101466");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainLabel = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddVehicle = new javax.swing.JPanel();
        btAddVehicle = new javax.swing.JButton();
        AddTrip2 = new javax.swing.JPanel();
        btAddEmployee = new javax.swing.JButton();
        AddTrip3 = new javax.swing.JPanel();
        btAddTrip = new javax.swing.JButton();
        AddTrip4 = new javax.swing.JPanel();
        btAssignDriver = new javax.swing.JButton();
        AddTrip5 = new javax.swing.JPanel();
        btGenerateReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainLabel.setBackground(new java.awt.Color(255, 255, 255));
        MainLabel.setForeground(new java.awt.Color(145, 137, 129));

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 0, 0));
        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(145, 137, 129));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manger");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome to Transportation Company System ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        AddVehicle.setBackground(new java.awt.Color(145, 137, 129));
        AddVehicle.setToolTipText("add Trip");

        btAddVehicle.setBackground(new java.awt.Color(145, 137, 129));
        btAddVehicle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAddVehicle.setForeground(new java.awt.Color(0, 0, 0));
        btAddVehicle.setText("Vehicles");
        btAddVehicle.setBorder(new javax.swing.border.MatteBorder(null));
        btAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddVehicleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddVehicleLayout = new javax.swing.GroupLayout(AddVehicle);
        AddVehicle.setLayout(AddVehicleLayout);
        AddVehicleLayout.setHorizontalGroup(
            AddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddVehicleLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        AddVehicleLayout.setVerticalGroup(
            AddVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddVehicleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        AddTrip2.setBackground(new java.awt.Color(145, 137, 129));
        AddTrip2.setToolTipText("add Trip");

        btAddEmployee.setBackground(new java.awt.Color(145, 137, 129));
        btAddEmployee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAddEmployee.setForeground(new java.awt.Color(0, 0, 0));
        btAddEmployee.setText("Add Employee");
        btAddEmployee.setBorder(new javax.swing.border.MatteBorder(null));
        btAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddTrip2Layout = new javax.swing.GroupLayout(AddTrip2);
        AddTrip2.setLayout(AddTrip2Layout);
        AddTrip2Layout.setHorizontalGroup(
            AddTrip2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTrip2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        AddTrip2Layout.setVerticalGroup(
            AddTrip2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTrip2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btAddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        AddTrip3.setBackground(new java.awt.Color(145, 137, 129));
        AddTrip3.setToolTipText("add Trip");

        btAddTrip.setBackground(new java.awt.Color(145, 137, 129));
        btAddTrip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAddTrip.setForeground(new java.awt.Color(0, 0, 0));
        btAddTrip.setText("Trips");
        btAddTrip.setBorder(new javax.swing.border.MatteBorder(null));
        btAddTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddTripActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddTrip3Layout = new javax.swing.GroupLayout(AddTrip3);
        AddTrip3.setLayout(AddTrip3Layout);
        AddTrip3Layout.setHorizontalGroup(
            AddTrip3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTrip3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btAddTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        AddTrip3Layout.setVerticalGroup(
            AddTrip3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTrip3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btAddTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        AddTrip4.setBackground(new java.awt.Color(145, 137, 129));
        AddTrip4.setToolTipText("add Trip");

        btAssignDriver.setBackground(new java.awt.Color(145, 137, 129));
        btAssignDriver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAssignDriver.setForeground(new java.awt.Color(0, 0, 0));
        btAssignDriver.setText("assign Driver");
        btAssignDriver.setBorder(new javax.swing.border.MatteBorder(null));
        btAssignDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAssignDriverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddTrip4Layout = new javax.swing.GroupLayout(AddTrip4);
        AddTrip4.setLayout(AddTrip4Layout);
        AddTrip4Layout.setHorizontalGroup(
            AddTrip4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddTrip4Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(btAssignDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        AddTrip4Layout.setVerticalGroup(
            AddTrip4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddTrip4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btAssignDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        AddTrip5.setBackground(new java.awt.Color(145, 137, 129));
        AddTrip5.setToolTipText("add Trip");

        btGenerateReport.setBackground(new java.awt.Color(145, 137, 129));
        btGenerateReport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btGenerateReport.setForeground(new java.awt.Color(0, 0, 0));
        btGenerateReport.setText("generate Report");
        btGenerateReport.setBorder(new javax.swing.border.MatteBorder(null));
        btGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerateReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddTrip5Layout = new javax.swing.GroupLayout(AddTrip5);
        AddTrip5.setLayout(AddTrip5Layout);
        AddTrip5Layout.setHorizontalGroup(
            AddTrip5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTrip5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btGenerateReport, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        AddTrip5Layout.setVerticalGroup(
            AddTrip5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTrip5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainLabelLayout = new javax.swing.GroupLayout(MainLabel);
        MainLabel.setLayout(MainLabelLayout);
        MainLabelLayout.setHorizontalGroup(
            MainLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLabelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(67, 67, 67))
            .addGroup(MainLabelLayout.createSequentialGroup()
                .addGroup(MainLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLabelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(MainLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddTrip3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddTrip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(MainLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainLabelLayout.createSequentialGroup()
                                .addComponent(AddVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(AddTrip4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AddTrip5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MainLabelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainLabelLayout.setVerticalGroup(
            MainLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLabelLayout.createSequentialGroup()
                .addGroup(MainLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLabelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(MainLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddTrip4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddTrip3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(MainLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddTrip5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddTrip2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void onClick(JPanel panel){
    panel.setBackground(Color.red);
   }
private void onLeaveClick(JPanel panel){
    panel.setBackground(Color.blue);
   }
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
         Login login = new Login ();
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_logoutActionPerformed

    private void btAddTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddTripActionPerformed
        // TODO add your handling code here:
        TripForm trip = new  TripForm  ();
        trip.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_btAddTripActionPerformed

    private void btAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddVehicleActionPerformed
        // TODO add your handling code here:
         AddvehicleForm A = new AddvehicleForm ();
        A.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btAddVehicleActionPerformed

    private void btAssignDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAssignDriverActionPerformed
        // TODO add your handling code here:
         assignDriverForm assign = new  assignDriverForm  ();
        assign.setVisible(true);
        this.dispose();
         
    }//GEN-LAST:event_btAssignDriverActionPerformed

    private void btAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddEmployeeActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        AddEmployee add = new  AddEmployee  ();
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btAddEmployeeActionPerformed

    private void btGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerateReportActionPerformed
       
        String tripReport = manager.generateTripReport();
        String vehicleReport = manager.generateVehicleReport();
        String employeeReport = manager.generateEmployeeReport();
        String report = tripReport + "\n" + vehicleReport + "\n" + employeeReport;
        JOptionPane.showMessageDialog(null, report, "Reports", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_btGenerateReportActionPerformed
 
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddTrip2;
    private javax.swing.JPanel AddTrip3;
    private javax.swing.JPanel AddTrip4;
    private javax.swing.JPanel AddTrip5;
    private javax.swing.JPanel AddVehicle;
    private javax.swing.JPanel MainLabel;
    private javax.swing.JButton btAddEmployee;
    private javax.swing.JButton btAddTrip;
    private javax.swing.JButton btAddVehicle;
    private javax.swing.JButton btAssignDriver;
    private javax.swing.JButton btGenerateReport;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
